spring.application.name=demo
server.port=8080

# SSL Ayarlar? (Docker daxilind?ki yola h?d?fl?nib)
server.ssl.key-store=file:/app/config/computer-sale.p12
server.ssl.key-store-password=${SSL_PASS}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=computer-sale

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT & Mail
application.jwt.spring.token=${JWT_SECRET}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}