version: "3.8"

services:
  computersatisi-app:
    build: .
    container_name: computersatisi-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      .env
    environment:
      SPRING_PROFILES_ACTIVE: development
    volumes:
      - /home/root123/ComputerSatisi2/files:/app/files