version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: computersatisi-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - computersatisi-net
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  computersatisi-app:
    build: .
    container_name: computersatisi-backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL: ${EMAIL}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - computersatisi-net
    volumes:
      - ./uploads:/app/uploads
      - ./computer-sale.p12:/app/config/computer-sale.p12  # Sertifikatı bağlayırıq

  computersatisi-frontend:
    build: /home/root123/ComputerSatisi2/frontEnd
    container_name: computersatisi-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - computersatisi-app
    networks:
      - computersatisi-net
    environment:
      # SSH tunel və SSL istifadə etdiyin üçün artıq https və localhost istifadə edə bilərsən
      - REACT_APP_API_URL=https://localhost:8080
      - NEXT_PUBLIC_API_URL=https://localhost:8080

networks:
  computersatisi-net:
    driver: bridge

volumes:
  mysql_data: