version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: computersatisi-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - computersatisi-net

  computersatisi-app:
    build: .
    container_name: computersatisi-backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env  # Docker-ə deyirik ki, dəyişənləri bu fayldan götürsün
    environment:
      # Burada SPRING_DATASOURCE_URL birbaşa .env-dən oxunacaq
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - computersatisi-net

networks:
  computersatisi-net:
    driver: bridge