name: Contabo Server Auto-Deploy

on:
  push:
    branches:
      - main  # Əsas branch-ın master-dirsə, bunu master et

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}  # Buranı 'password' yerinə 'key' etdik
          script: |
            cd ~/ComputerSatisi2
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker image prune -f
